---
- hosts: all
  any_errors_fatal: true
  tasks:
    - name: start
      debug:
        msg: "Start Rebuild"
        verbosity: 1
        
    - name: import role hashicorp vault | uninstall
      import_role:
        name: role_hashicorp_vault
      vars:
        rl_hashicorp_vault_action: uninstall

    - name: import role hashicorp vault | install
      import_role:
        name: role_hashicorp_vault
      vars:
        rl_hashicorp_vault_action: install