---
- name: "{{ role_name }} | Get Services"
  service_facts:
  register: firewalld_state

- name: "{{ role_name }} | firewall state {{ rl_hashicorp_vault_firewalld_state }}"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: "{{ rl_hashicorp_vault_firewalld_state | default('enabled') }}"
    immediate: yes
  loop:
    - "{{ rl_hashicorp_vault_port }}/tcp"
    - "{{ rl_hashicorp_vault_port_cluster }}/tcp"
  when:
    - firewalld_state.ansible_facts.services.firewalld.service is defined